image:
  repository: chartmuseum/chartmuseum
  tag: v0.8.0
  pullPolicy: IfNotPresent
env:
  open:
    # storage backend, can be one of: local, alibaba, amazon, google, microsoft
    STORAGE: microsoft
    # container to store charts for microsoft storage backend
    STORAGE_MICROSOFT_CONTAINER: helm-charts
    # prefix to store charts for microsoft storage backend
    STORAGE_MICROSOFT_PREFIX:
    CHART_POST_FORM_FIELD_NAME: chart
    # form field which will be queried for the provenance file content
    PROV_POST_FORM_FIELD_NAME: prov
    # disable all routes prefixed with /api
    DISABLE_API: false
    # allow chart versions to be re-uploaded
    ALLOW_OVERWRITE: true
    # absolute url for .tgzs in index.yaml
    CHART_URL:
    # allow anonymous GET operations when auth is used
    AUTH_ANONYMOUS_GET: false
  secret:
    # username for basic http authentication
    BASIC_AUTH_USER: ""
    # password for basic http authentication
    BASIC_AUTH_PASS: ""
    AZURE_STORAGE_ACCOUNT: "" ## azure storage account
    AZURE_STORAGE_ACCESS_KEY: "" ## azure storage account access key
service:
  type: ClusterIP
  # clusterIP: None
  externalPort: 80
  nodePort:
  annotations: {}
resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 80m
#    memory: 64Mi

## Ingress for load balancer
ingress:
  enabled: true
# Chartmuseum Ingress annotations
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"

## Chartmuseum Ingress hostnames
## Must be provided if Ingress is enabled
##
  hosts:
    - name: chartmuseum.teraception.com
      path: /
      tls: true